---
title: "Inference Impact Sensor Lifetime Analysis"
author: "Davide"
date: "2025-10-17"
output:
  pdf_document:
    fig_width: 4
    fig_height: 2.5
  html_document:
    df_print: paged
  word_document: default
  html_notebook: default
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```


```{r}
library(survival)
library(dplyr)
library(lubridate)

data <- read.csv("DirtSlurper3100.csv", skip = 12, na.strings = "---", stringsAsFactors = FALSE)

data$Registration.date <- dmy(data$Registration.date)
data$Failure.date <- dmy(data$Failure.date)

dim(data)
head(data, 3)
```

```{r filter-data}

# Indicator for Impact sensor failure (1 if failed, 0 if censored)
data_filtered <- data %>%
  mutate(
    Event = ifelse(!is.na(Impact.status) & grepl("^\\s*damage\\s*$", Impact.status, ignore.case = TRUE), 1, 0)
  ) %>%
  filter(!is.na(Total.usage.time))

dim(data_filtered)
table(data_filtered$Event) # 0 = censored, 1 = event
summary(data_filtered$Total.usage.time)

str(data_filtered$Total.usage.time)
```

 

```{r KM plot}
KM_fit <- survfit(Surv(Total.usage.time, Event) ~ 1, data = data_filtered)
plot(KM_fit, conf.int = TRUE,
     xlab = "Usage time (hours)", ylab = "Survival probability",
     main = "Kaplan-Meier Impact sensor survival")

KM_fit

summary(KM_fit, times = c(1000, 2000, 2500, 3000, 3500, 3819))



```

```{r NA plot}
# Nelson–Aalen cumulative hazard
na_df <- with(KM_fit, data.frame(
  time     = time,
  n_risk   = n.risk,
  n_event  = n.event
))
na_df$cumhaz <- cumsum(na_df$n_event / na_df$n_risk)

plot(na_df$time, na_df$cumhaz, type = "s",
     xlab = "Usage time (hours)", ylab = "Cumulative hazard",
     main = "Nelson–Aalen cumulative hazard - Impact Sensor")

```


## Non-parametric Survival Estimates

```{r NA estimate}
# Nelson-Aalen cumulative hazard estimate 
km_times <- KM_fit$time # times of events
n_event <- KM_fit$n.event # number of events at each event time
n_risk <- KM_fit$n.risk # number at risk just before each event time

# Cumulative hazard H(t)
cum_hazard <- cumsum(n_event / n_risk)
# Combine times and cumulative hazard for output
na_estimate <- data.frame(Time = km_times, CumHazard = cum_hazard)
tail(na_estimate, 5)
```


## Parametric Survival Modeling

```{r weibull-fit}
# survreg(weibull) requires strictly positive times
df_weibull <- subset(data_filtered, Total.usage.time > 0)
weibull_fit <- survreg(Surv(Total.usage.time, Event) ~ 1, data = df_weibull, dist = "weibull")
summary(weibull_fit)
```

```{r weibull-params}
weibull_shape <- 1 / weibull_fit$scale  # beta (shape)
weibull_scale <- exp(coef(weibull_fit)) # alpha (scale)

cat("Weibull beta:", weibull_shape, "\n")
cat("Weibull alpha:", weibull_scale, "hours \n")

# Calculate L10 life (time by which 10% have failed, i.e. S(t)=0.90)
L10 <- weibull_scale * (-log(0.9))^(1 / weibull_shape)
cat("Estimated L10 life:", L10, "hours \n")
```

```{r}
KM_fit_diag <- survfit(Surv(Total.usage.time, Event) ~ 1, data = df_weibull)
idx <- which(KM_fit_diag$surv > 0 & KM_fit_diag$surv < 1)
x <- log(KM_fit_diag$time[idx])
y <- log(-log(KM_fit_diag$surv[idx]))

plot(x, y, pch = 20,
     xlab = "log(time)", ylab = "log(-log(Survival))",
     main = "Weibull sanity check with log-log plot - Impact Sensor")
abline(a = - weibull_shape * log(weibull_scale), b = weibull_shape, lty = 2, lwd = 2, col="blue")
```




